# Generated by Django 3.0.7 on 2020-07-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('number', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('inquiry', models.TextField(null=True)),
            ],
        ),
    ]
